config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
  end

  root 'products#index'
  resources :products, only: [:index, :new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :product
  has_attached_file :image, :styles => { large: '600x600>', medium: '300x300>', thumb: '150x150#' },
                    :path => ":rails_root/public/system/products/images/:style/:basename.:extension",
                    :url => "/system/products/images/:style/:basename.:extension"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :attachments


  validates_presence_of :name, :description

  def files=(array_of_files = [])
    array_of_files.each do |f|
      attachments.build(image: f, product: self)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  before_action :set_product, only: [:show]
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product[:user_id] = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

  def set_product
    @product = Product.find_by(id: params[:id])
  end
  def product_params
    params.require(:product).permit(:name, :description, files: [])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_name(name)
    name.split.map(&:capitalize).join(' ')
  end
end

app/views/layouts/_flash_message.html.erb
<div class="col-md-6 offset-md-3 flash_message">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %> alert-dismissible" role="alert">
			<%= value %>
		</div>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">Awesome Products</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ms-auto">
				<li class="nav-item">
					<%= link_to 'Add product', new_product_path, class: "nav-link active", "aria-current": "page" %>
				</li>
				<% if user_signed_in? %>
					<li class="nav-item">
						<%= link_to("Logout", destroy_user_session_path, method: :delete, class: "nav-link active", "aria-current": "page" ) %>
					</li>
				<% else %>
					<li class="nav-item">
						<%= link_to('Login', new_user_session_path, class: "nav-link active", "aria-current": "page" ) %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AwesomeProducts</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<link href="https://fonts.googleapis.com/css2?family=Arimo&display=swap" rel="stylesheet">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<%= render 'layouts/flash_message' %>
	<%= yield %>
</div>
</body>
</html>

app/views/products/index.html.erb
<div class="main">
	<div class="row title">
		<h2>Products List</h2>
	</div>
	<div class="products">
		<div class="card-deck">
			<% @products.each do |product| %>
				<div class="card">
					<%= image_tag(product.attachments.first.image.url(:medium), class: "card-img-top", alt: "Card image cap") %>
					<div class="card-body">
						<h5 class="card-title"><%= link_to format_name(product.name), product_path(product) %></h5>
						<p class="card-text"><%= product.description.truncate(100) %></p>
					</div>
					<div class="card-footer">
						<small class="text-muted"> <%=link_to 'Details', product_path(product) %></small>
					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>

app/views/products/new.html.erb
<div class="col-md-6 offset-md-3">
	<div class="row shadow p-3 mb-5 bg-white rounded main_form">
		<div class="row header">
			<h2> Add product</h2>
		</div>
		<div class="row">
			<%= simple_form_for(@product) do |f| %>
				<div class="field">
					<%= f.input :name, placeholder: 'Name', label: false %>
				</div>
				<div class="field">
					<%= f.input :description, as: :text, placeholder: 'Description', label: false, :input_html => { class: 'test', :cols => 5, :rows => 5 } %>
				</div>
				<div class="field">
					<%= f.input :files, as: :file, label: false, input_html: { :multiple => true } %>
				</div>
				<div class="col-md-4 offset-md-4">
					<div class="actions">
						<%= f.button :submit, "Submit", class: "btn btn-primary"%>
					</div>
				</div>
				
			<% end %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="main">
	<div class="row title">
		<h2> Product details</h2>
	</div>
	<div class="products">
		<h3> <%= format_name(@product.name) %> </h3>
		<div class="row">
			<div class="col-md-5">
				<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
					<ol class="carousel-indicators">
						<% @product.attachments.each.with_index(0) do |image, index| %>
							<li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
						<% end %>
					</ol>
					<div class="carousel-inner">
						<% @product.attachments.each.with_index(0) do |image, index| %>
							<div class="carousel-item <%= index.zero? ? 'active' : '' %>">
								<%= image_tag image.image.url(:large) %>
							</div>
						<% end %>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</a>
				</div>
			</div>
			<div class="col-md-7">
				<%= @product.description %>
			</div>
		</div>
	</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>


<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>